name: DreamLand
main: me.cmesh.DreamLand.DreamLand
version: 3.5
commands:
   wakeup:
      description: User will leave the dream they are in
      usage: |
          /wakeup
   setdreamspawn:
      description: User will set the world's spawn location
      usage: |
          /setdreamspawn