name: DreamLand
main: me.cmesh.DreamLand.DreamLand
version: 4.2
author: AKP and some other guy who didn't have his name in the plugin.yml.
softdepend: [SmoothFlight]
commands:
   wakeup:
      description: User will leave the dream they are in
      usage: |
          /wakeup
   setdreamspawn:
      description: User will set the world's spawn location
      usage: |
          /setdreamspawn
   dream:
      description: Hush little baby, don't say a word... and nevermind that noise you heard...
      usage: /dream
